name: my first workflow
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome meassage
        run: echo "welcome to the world of github actions"
  
    