name: My First Workflow

on:
  push:

jobs:
  configure-aws:
    runs-on: ubuntu-latest

    steps:
      - name: AWS key setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ap-south-1
      - name: aws cli check
        run: aws --version
      - name: s3 bucket list
        run: aws s3 ls  
